build-PythonLogsApiLayer:
	cp -r extensions $(ARTIFACTS_DIR)
	python3 -m pip install -r requirements.txt -t $(ARTIFACTS_DIR)/extensions
	chmod +x $(ARTIFACTS_DIR)/extensions/logs_api_http_extension.py
